name: Coverity Scan
on:
  workflow_dispatch:
  schedule:
    - cron: '0 9 * * 5'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          submodules: true
      - uses: actions/cache@v3
        id: coverity-toolchain-cache
        with:
          path: cov-analysis-linux64
          key: ${{ runner.os }}-coverity
      - name: Install stuff
        run: ./tests/ci/install.sh
      - name: Download Coverity Scan
        if: steps.coverity-toolchain-cache.outputs.cache-hit != 'true'
        run: |
          wget -q https://scan.coverity.com/download/cxx/linux64 \
               --post-data "token=$TOKEN&project=vincentbernat%2Flldpd" \
               -O cov-analysis-linux64.tar.gz
          mkdir cov-analysis-linux64
          tar xzf cov-analysis-linux64.tar.gz --strip 1 -C cov-analysis-linux64
        env:
          TOKEN: ${{ secrets.COVERITY_SCAN_TOKEN }}
      - name: Build
        run: |
          ./autogen.sh
          ./configure --with-snmp
          export PATH=`pwd`/cov-analysis-linux64/bin:$PATH
          cov-build --dir cov-int make
      - name: Submit the result to Coverity Scan
        run: |
          tar czvf lldpd.tgz cov-int
          curl \
            --form project=vincentbernat-lldpd \
            --form token=$TOKEN \
            --form email=vincent@bernat.ch \
            --form file=@lldpd.tgz \
            --form version=trunk \
            --form description="lldpd $(git rev-parse HEAD)" \
            https://scan.coverity.com/builds?project=vincentbernat%2Flldpd
        env:
          TOKEN: ${{ secrets.COVERITY_SCAN_TOKEN }}
